@BASE_URL= http://localhost:3000/api



### @name GET ALL USERS 
GET {{BASE_URL}}/users



### GET SPECIFIC USER ( ONLY ONE )
GET {{BASE_URL}}/users/2



### POST NEW USER
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name" : "osman",
    "userName" :"username",
    "email":"osman@gmail.com",
    "password":"123123"
}

### LOGIN
POST {{BASE_URL}}/users/login
Content-Type: application/json

{
    "email":"osman@gmail.com",
    "password":"123123"
}


### UPDATE SPECIFIC USER 
PATCH {{BASE_URL}}/users/629f9d6d5e9db75d5d3c0223
Content-Type: application/json

{
    "password":"newPassword"
}




### DELETE SPECIFIC USER
DELETE {{BASE_URL}}/users/62952af5bc69b46919efc7e4



