@BASE_URL= http://localhost:3000/api



### @name GET ALL USERS 
GET {{BASE_URL}}/users



### GET SPECIFIC USER ( ONLY ONE )
GET {{BASE_URL}}/users/2



### POST NEW USER
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name" : "osman1",
    "userName" :" osmnkiraz111",
    "email":"osmnkiraz111@gmail.com",
    "password":"1231231231"
}



### UPDATE SPECIFIC USER 
PATCH {{BASE_URL}}/users/62952af5bc69b46919efc7e5
Content-Type: application/json

{
    "name":"1111231",
    "email":"osmnkiraz111@gmail.com"
}




### DELETE SPECIFIC USER
DELETE {{BASE_URL}}/users/62952af5bc69b46919efc7e4



