@BASE_URL= http://localhost:3000/api
@TOKEN =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmE3ODNhNTI2Y2QzMzQ0ZjU5MmQ3NTgiLCJpYXQiOjE2NTUxNDU0OTQsImV4cCI6MTY1NTE0OTA5NH0.NRgeyY-lmcdWO-stZqpAP4hnNP3cqkIZVPLzlYxDLX8


### @name GET ALL USERS 
GET {{BASE_URL}}/users
Authorization: Bearer {{TOKEN}}


### GET SPECIFIC USER ( ONLY ONE )
GET {{BASE_URL}}/users/2



### POST NEW USER
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name" : "osman2",
    "userName" :"username2",
    "email":"osman2@gmail.com",
    "password":"123123"
}

### LOGIN
POST {{BASE_URL}}/users/login
Content-Type: application/json

{
    "email":"osman2@gmail.com",
    "password":"123123"
}


### UPDATE SPECIFIC USER 
PATCH {{BASE_URL}}/users/629f9d6d5e9db75d5d3c0223
Content-Type: application/json

{
    "password":"newPassword"
}


### UPDATE ME
PATCH {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjlmYTk5YTExZTI3NWVhZmIxNjE1MjEiLCJpYXQiOjE2NTQ4MDA5OTcsImV4cCI6MTY1NDgwNDU5N30.WKWKp6rAeMsJG98WIkFsm4j_EXlKsVDjQy0bYEDWv3U

{
    "email":"UpdatedMail@gmail.com"
}




### DELETE SPECIFIC USER
DELETE {{BASE_URL}}/users/62952af5bc69b46919efc7e4



### DELETE ALL USERS
DELETE {{BASE_URL}}/users/deleteAll
Authorization: Bearer {{TOKEN}}



### DELETE YOU
DELETE {{BASE_URL}}/users/me
Authorization: Bearer {{TOKEN}}


